### ISSUE TITLE
Задание новичку

### ISSUE THREAD

**Issue by Lyumih** [hcodes/eyo-kernel#11]
Добрый день!
Понравился ваш проект.
Я хочу влиться в open-source. 
У вас есть какое-нибудь задание для новичка?
Могу я расчитывать на менторство от вас при отправке пулл-реквеста.

**Comment by hcodes** [comment]
Привет.
Можно начать с hcodes/eyo#15, а продолжить hcodes/eyo#21.
Ещё есть вариант — https://cultofmartians.com/

**Comment by hcodes** [comment]
/cc @Lyumih 
Остались ещё вопросы?
