### ISSUE TITLE
Возможная неточность (тер/тёр)

### ISSUE THREAD

**Issue by dima74** [hcodes/eyo-kernel#14]
https://github.com/hcodes/eyo-kernel/blob/b47bf6306dd2861c17954ffadedbfc226779a37c/dict_src/safe.txt#L13038

Слово `тёр` кажется может писаться и через `е`: 
* https://ru.wiktionary.org/wiki/тер
* https://ru.wikipedia.org/wiki/Баттьяни_тер_(станция_метро)

**Comment by hcodes** [comment]
Тер — спорное слово.
А вот со станцей метро необходим контекст, который сейчас в `eyo `не поддерживается.

**Comment by hcodes** [comment]
https://github.com/hcodes/eyo-kernel/issues/15
