### ISSUE TITLE
Полнота словарей

### ISSUE THREAD

**Issue by gwer** [hcodes/eyo-kernel#2]
А что насчёт матерных слов? Они принципиально отсутствуют в словарях? Всё-таки важный момент. Вдруг какой-нибудь долбо**_е_**б будет ёфицировать текст, всё ёфицирует, а себе подобных не ёфицирует. И текст получится ху**_е_**вым. 

PS: Прошу прощения за лексику, нужна была демонстрация проблемы.

**Comment by AlexWayfer** [comment]
Употребление мата хоть и [не допускается общественной моралью](https://ru.wikipedia.org/wiki/Русский_мат), но это всё же [сегмент лексики языка](https://ru.wikipedia.org/wiki/Обсценная_лексика_в_русском_языке), так что поддерживаю.

**Comment by ai** [comment]
Я тоже поддерживаю, если нет нет рациональных причин

**Comment by hcodes** [comment]
Согласен, плюсую. :)

**Comment by hcodes** [comment]
Шутки шутками, но составлять и поддерживать словарь матерных слов не буду.

**Comment by AlexWayfer** [comment]
Может тогда откроем issue для расширения сторонними словарями? Тип плагинов. В README не нашёл информации на этот счёт.

**Comment by hcodes** [comment]
Конечно можно.
